#!/usr/bin/env bash

COLOR=yes
RES_COL=$(($(tput cols) - 8)) #Screen width
MOVE_TO_COL="echo -en \\033[${RES_COL}G"
SETCOLOR_SUCCESS="echo -en \\033[1;32m"
SETCOLOR_FAILURE="echo -en \\033[1;31m"
SETCOLOR_WARNING="echo -en \\033[1;33m"
SETCOLOR_NORMAL="echo -en \\033[0;39m"



echo_success() {
	$MOVE_TO_COL
	echo -n "["
	[ "$COLOR" = "yes" ] && $SETCOLOR_SUCCESS
	echo -n $"  OK  "
	[ "$COLOR" = "yes" ] && $SETCOLOR_NORMAL
	echo -n "]"
	echo -ne "\r"
	return 0
}
 
echo_failure() {
	$MOVE_TO_COL
	echo -n "["
	[ "$COLOR" = "yes" ] && $SETCOLOR_FAILURE
	echo -n $"FAILED"
	[ "$COLOR" = "yes" ] && $SETCOLOR_NORMAL
	echo -n "]"
	echo -ne "\r"
	return 1
}

echo_passed() {
	$MOVE_TO_COL
	echo -n "["
	[ "$COLOR" = "yes" ] && $SETCOLOR_WARNING
	echo -n $"PASSED"
	[ "$COLOR" = "yes" ] && $SETCOLOR_NORMAL
	echo -n "]"
	echo -ne "\r"
	return 1
}
 
echo_warning() {
	$MOVE_TO_COL
	echo -n "["
	[ "$COLOR" = "yes" ] && $SETCOLOR_WARNING
	echo -n $"WARNING"
	[ "$COLOR" = "yes" ] && $SETCOLOR_NORMAL
	echo -n "]"
	echo -ne "\r"
	return 1
}


#Colors
BLACK="\033[0;30m"
RED="\033[0;31m"
GREEN="\033[0;32m"
BROWN="\033[0;33m"
BLUE="\033[0;34m"
PURPLE="\033[0;35m"
CYAN="\033[0;36m"
LIGHT_GRAY="\033[0;37m"
GRAY="\033[1;30m"
LIGHT_RED="\033[1;31m"
LIGHT_GREEN="\033[1;32m"
YELLOW="\033[1;33m"
LIGHT_BLUE="\033[1;34m"
LIGHT_PURPLE="\033[1;35m"
LIGHT_CYAN="\033[1;36m"
WHITE="\033[1;36m"

NORMAL=$LIGHT_GRAY
OK=$GREEN
WARNING=$YELLOW
ALERT=$RED

msg_alert ()
{
    echo -e "${ALERT}${1}${NORMAL}"
}

msg_warning()
{
    echo -e "${WARNING}${1}${NORMAL}"
}

msg_ok()
{
    echo -e "${OK}${1}${NORMAL}"
}


###################################
## Examples
###################################

#msg_alert "Buff, menudo error."
#msg_warning "Cuidado, hay algo que no ha ido del todo bien."
#msg_ok "Esto significa que ha ido bien."


#echo -n "Ejecutando ls..."
#sleep 2
#ls -la > /dev/null 2>&1
#if [ $? -eq 0 ]; then echo_success ; echo; else echo_failure ; echo; fi

#echo -n "Creando directorio '/tmp/melon'..."
#sleep 4
#mkdir /tmp/melon > /dev/null 2>&1
#if [ $? -eq 0 ]; then echo_success ; echo; else echo_failure ; echo; fi

#echo -n "Borrando directorio '/tmp/melon'..."
#sleep 5
#rm -R /tmp/melon > /dev/null 2>&1
#if [ $? -eq 0 ]; then echo_success ; echo; else echo_failure ; echo; fi

#echo -n "Creando directorio '/esto/va/a/fallar'..."
#sleep 3
#mkdir /esto/va/a/fallar > /dev/null 2>&1
#if [ $? -eq 0 ]; then echo_success ; echo; else echo_failure ; echo; fi

